import Head from "next/head";
import { useState } from "react";
import App from "../pages/projectCard.js";
import { useSession } from "@supabase/auth-helpers-react";
export default function Home() {
  const array = [
    { projectID: 1, projectName: "First Project" },
    { projectID: 2, projectName: "Second Project" },
    { projectID: 3, projectName: "Third  Project" },
    { projectID: 4, projectName: "fourth  Project" },
    { projectID: 5, projectName: "fifth Project" },
    { projectID: 6, projectName: "sixth  Project" },
    { projectID: 7, projectName: "seventh  Project" },
  ];

  function showCard(val) {
    return (
      <App>
        projectID = {val.projectID}
        projectName= {val.projectName}
      </App>
    );
  }
  return (
    <div>
      <Head>
        <title>Frostbyte</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <div>
          <h1 className='text-5xl font-bold bg-gray-200 text-center'>
            Frostbyte
          </h1>
          <br></br>
        </div>
        {array.map(showCard)}
      </main>
    </div>
  );
}
