import Head from "next/head";
import { useSession } from "@supabase/auth-helpers-react"

export default function Home() {

  return (
    <div>
      <Head>
        <title>Frostbyte</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <h1 className='text-5xl font-bold bg-gray-200 text-center'>
          Frostbyte
        </h1>
      </main>
    </div>
  );
}
