FROM apache/kafka:3.7.0

EXPOSE 9092

ENV KAFKA_BROKER_ID=1
ENV KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
ENV KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
ENV KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://:9092
ENV KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1

# Start Kafka as the default command
CMD ["bin/kafka-server-start.sh", "config/server.properties"]
